name: ESLint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.3.0'

      - name: Run ESLint
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          npx eslint .  # Run ESLint on the current directory
