name: ESLint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.3.0'

      - name: Run ESLint
        run: |
          output=$(npx eslint .)
          echo "$output"
          if [ $? -ne 0 ]; then
            echo "ESLint found issues. Exiting with error."
            exit 1
          fi
